# Generated by Django 3.1.4 on 2020-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('author', models.CharField(max_length=30, null=True)),
                ('url', models.CharField(max_length=30, null=True, unique=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='stores')),
            ],
        ),
    ]
