# Generated by Django 3.1.4 on 2020-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201209_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgl_project',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='webgl_project',
            name='thumbnail',
            field=models.ImageField(default='thumbnail_default.jpg', null=True, upload_to='thumbnail'),
        ),
    ]
